version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./config.php:/var/www/html/config.php
      - ./db:/var/www/html/db
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data